name: healthy_scanner
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Kakao SDK
  kakao_flutter_sdk_user: ^1.8.0
  kakao_flutter_sdk_common: ^1.8.0

  # Networking
  http: ^1.2.0

  # State management
  get: ^4.6.6

  # Kakao REST ë¡œê·¸ì¸ â†’ URLLauncher í•„ìš”
  url_launcher: ^6.1.10

  # ðŸ”¥ uni_links 0.5.1 â†’ AGP 8.x í™˜ê²½ì—ì„œ ì˜¤ë¥˜ ë°œìƒ
  # ë”°ë¼ì„œ AGP8 í˜¸í™˜ í¬í¬ ë²„ì „ ì‚¬ìš©
  uni_links:
    git:
      url: https://github.com/dzulfiqarleo/uni_links_fix_agp8.git

  # ë³´ì•ˆ ì €ìž¥
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#FF5938"
  image: assets/images/logo.png
  android_12:
    color: "#FF5938"
    image: assets/images/logo.png
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
